# Generated by Django 2.1.7 on 2019-03-07 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField(help_text='Start of rain event in simulation (ISO 8601 format)')),
                ('active_till', models.DateTimeField(help_text='End of rain event in simulation (ISO 8601 format)', null=True)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationMeta',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_slug', models.SlugField(max_length=120)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RainDesignEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threedi_events.BaseEvent')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            bases=('threedi_events.baseevent',),
        ),
        migrations.CreateModel(
            name='RainRadarEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threedi_events.BaseEvent')),
                ('multiplier', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('layer', models.UUIDField(help_text='UUID of the raster-store rain layer')),
                ('start', models.DateTimeField(help_text='The radar rain start time in ISO 8601 format')),
            ],
            bases=('threedi_events.baseevent',),
        ),
        migrations.CreateModel(
            name='RainTimeseriesEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threedi_events.BaseEvent')),
                ('source', models.CharField(max_length=80)),
                ('source_uuid', models.CharField(max_length=40)),
                ('start', models.DateTimeField()),
            ],
            bases=('threedi_events.baseevent',),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threedi_events.SimulationMeta'),
        ),
    ]
